### ISSUE TITLE
Configure your Omni Core server ??? where???

### ISSUE THREAD

**Issue by Govind13100** [OmniLayer/OmniClientJS#5]
Configure your Omni Core server
There are a few bitcoin.conf settings that are necessary to run these tests.

Run on the Bitcoin TestNet:

testnet=1

Tell Bitcoin/OmniCore to accept JSON-RPC commands.:

server=1

Set a username and password for RPC:

rpcuser=test-username-goes-here rpcpassword=test-password-goes-here

Where to put all this ??

**Comment by msgilligan** [comment]
*Omni Core* is based on *Bitcoin Core* and when installed uses the same `bitcoin.conf` configuration  file as is used by Bitcoin.

See:

* https://en.bitcoin.it/wiki/Running_Bitcoin
• https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/configuration.md

**Comment by msgilligan** [comment]
This information was added to the `README.md` file: a9c2d757ce3fd917027cf699c8474cfb36eac247
