### ISSUE TITLE
is this package alive?

### ISSUE THREAD

**Issue by callmez** [OmniLayer/OmniClientJS#7]
no npm package?
old dependencies?

**Comment by dexX7** [comment]
Hi @callmez,

as far as I know this project isn't maintained anymore.

**Comment by msgilligan** [comment]
Yes, this package is currently unmaintained. We are open to a new maintainer stepping forward.

**Comment by luongnguyenduc** [comment]
Hi @msgilligan, so what client should I use now to work with Omni layer? thank you.
